/// Bilingual governorate list (MVP subset; full 27 land post-MVP).
const governorates = [
  ('القاهرة', 'Cairo'),
  ('الجيزة', 'Giza'),
  ('الإسكندرية', 'Alexandria'),
  ('الدقهلية', 'Dakahlia'),
  ('الشرقية', 'Sharqia'),
  ('الغربية', 'Gharbia'),
  ('المنوفية', 'Monufia'),
  ('القليوبية', 'Qalyubia'),
  ('البحيرة', 'Beheira'),
  ('كفر الشيخ', 'Kafr El Sheikh'),
  ('دمياط', 'Damietta'),
  ('بورسعيد', 'Port Said'),
  ('الإسماعيلية', 'Ismailia'),
  ('السويس', 'Suez'),
  ('الفيوم', 'Faiyum'),
  ('بني سويف', 'Beni Suef'),
  ('المنيا', 'Minya'),
  ('أسيوط', 'Asyut'),
  ('سوهاج', 'Sohag'),
  ('قنا', 'Qena'),
  ('الأقصر', 'Luxor'),
  ('أسوان', 'Aswan'),
  ('البحر الأحمر', 'Red Sea'),
  ('الوادي الجديد', 'New Valley'),
  ('مطروح', 'Matrouh'),
  ('شمال سيناء', 'North Sinai'),
  ('جنوب سيناء', 'South Sinai'),
];
